server:
    port: 8443
    ssl:
      enabled: true
      key-store-type: PKCS12
      key-store: /home/quocthang12/Desktop/leonardo_spring_boot/src/main/resources/leonardo.p12
      key-store-password: quocthang123
      key-alias: leonardo
logging:
    level:
      root: INFO
leonardo:
    url: mongodb://localhost:27017/leonardo
    username: quocthang123
    password: quocthang123
    database: leonardo
spring:
    servlet:
      multipart:
        max-file-size: 5MB 
        max-request-size: 5MB
    mail:
      host: smtp.gmail.com
      port: 587
      username: quocthang1100@gmail.com
      password: tvcrpatjffoboxxf
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
    security:
      oauth2:
        client:
          registration:
            github:
              clientId: 7ef49387374e54acbffb
              clientSecret: d4b763efa76df8a46029195e7a1fc2094ce64a42
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - user:email
                - read:user
            google:
              clientId: 876238461575-p909dmpn8rd9ng1dtui506j0cclicj8d.apps.googleusercontent.com
              clientSecret: Tx2WSltWNkBbr5b0ERT0aJWh
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
              scope:
                - email
                - profile
            facebook:
              clientId: 217204193795153
              clientSecret: f2db2c8c4f9683beec62662a57a95776
              redirectUri: "{baseUrl}/oauth2/callback/{registrationId}" 
              scope:
                - email
                - public_profile
          provider:
            facebook:
              authorizationUri: https://www.facebook.com/v11.0/dialog/oauth
              tokenUri: https://graph.facebook.com/v11.0/oauth/access_token
              userInfoUri: https://graph.facebook.com/v11.0/me?fields=email,first_name,middle_name,last_name,name,picture.width(250).height(250)
              